export interface Medicine {
  id: string
  name: string
  genericName: string
  brand: string
  strength: string
  form: string
  price: number
  manufacturer: string
  description: string
  uses: string[]
  sideEffects: string[]
  dosage: string
  precautions: string[]
  category: string
  prescriptionRequired: boolean
  availability: "In Stock" | "Out of Stock" | "Limited Stock"
  conditions: string[]
  barcode: string
}

export const medicineDatabase: Medicine[] = [
  // Existing sample (trimmed down copy of your previous, kept and expanded with new entries)
  {
    id: "1",
    name: "Paracetamol",
    genericName: "Acetaminophen",
    brand: "Crocin",
    strength: "500mg",
    form: "Tablet",
    price: 25,
    manufacturer: "GSK",
    description: "Pain reliever and fever reducer",
    uses: ["Fever", "Headache", "Body pain", "Toothache"],
    sideEffects: ["Nausea", "Stomach upset", "Allergic reactions"],
    dosage: "1-2 tablets every 4-6 hours, max 8 tablets per day",
    precautions: ["Do not exceed recommended dose", "Avoid alcohol", "Consult doctor if pregnant"],
    category: "Analgesic",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["fever", "headache", "pain", "toothache", "body ache", "muscle pain"],
    barcode: "8901030001234",
  },
  {
    id: "2",
    name: "Ibuprofen",
    genericName: "Ibuprofen",
    brand: "Brufen",
    strength: "400mg",
    form: "Tablet",
    price: 45,
    manufacturer: "Abbott",
    description: "Anti-inflammatory pain reliever",
    uses: ["Pain", "Inflammation", "Fever", "Arthritis"],
    sideEffects: ["Stomach irritation", "Nausea", "Dizziness"],
    dosage: "1 tablet every 6-8 hours with food",
    precautions: ["Take with food", "Avoid if stomach ulcers", "Monitor blood pressure"],
    category: "NSAID",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["joint pain", "arthritis", "inflammation", "back pain", "muscle strain", "sports injury"],
    barcode: "8901030002341",
  },
  {
    id: "3",
    name: "Aspirin",
    genericName: "Acetylsalicylic Acid",
    brand: "Disprin",
    strength: "325mg",
    form: "Tablet",
    price: 20,
    manufacturer: "Reckitt Benckiser",
    description: "Pain reliever and blood thinner",
    uses: ["Pain", "Fever", "Heart protection", "Stroke prevention"],
    sideEffects: ["Stomach bleeding", "Nausea", "Ringing in ears"],
    dosage: "1-2 tablets every 4 hours for pain, 1 tablet daily for heart protection",
    precautions: ["Not for children under 16", "Take with food", "Monitor for bleeding"],
    category: "Analgesic",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["headache", "fever", "heart disease", "stroke prevention", "chest pain"],
    barcode: "8901030003458",
  },
  {
    id: "4",
    name: "Metformin",
    genericName: "Metformin HCl",
    brand: "Glycomet",
    strength: "500mg",
    form: "Tablet",
    price: 85,
    manufacturer: "USV",
    description: "Diabetes medication to control blood sugar",
    uses: ["Type 2 Diabetes", "PCOS", "Insulin resistance"],
    sideEffects: ["Nausea", "Diarrhea", "Metallic taste", "Vitamin B12 deficiency"],
    dosage: "500mg twice daily with meals",
    precautions: ["Monitor kidney function", "Take with food", "Regular blood sugar monitoring"],
    category: "Antidiabetic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["diabetes", "high blood sugar", "type 2 diabetes", "insulin resistance", "pcos"],
    barcode: "8901030004565",
  },
  {
    id: "5",
    name: "Glimepiride",
    genericName: "Glimepiride",
    brand: "Amaryl",
    strength: "2mg",
    form: "Tablet",
    price: 120,
    manufacturer: "Sanofi",
    description: "Sulfonylurea for diabetes management",
    uses: ["Type 2 Diabetes", "Blood sugar control"],
    sideEffects: ["Hypoglycemia", "Weight gain", "Nausea"],
    dosage: "1-2mg once daily with breakfast",
    precautions: ["Monitor blood sugar", "Risk of hypoglycemia", "Regular meal timing"],
    category: "Antidiabetic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["diabetes", "type 2 diabetes", "high blood sugar", "diabetic control"],
    barcode: "8901030005672",
  },
  {
    id: "6",
    name: "Insulin Glargine",
    genericName: "Insulin Glargine",
    brand: "Lantus",
    strength: "100 units/ml",
    form: "Injection",
    price: 850,
    manufacturer: "Sanofi",
    description: "Long-acting insulin for diabetes",
    uses: ["Type 1 Diabetes", "Type 2 Diabetes", "Insulin therapy"],
    sideEffects: ["Hypoglycemia", "Injection site reactions", "Weight gain"],
    dosage: "As prescribed by doctor, usually once daily",
    precautions: ["Proper injection technique", "Rotate injection sites", "Monitor blood sugar"],
    category: "Insulin",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["type 1 diabetes", "type 2 diabetes", "insulin dependent diabetes", "severe diabetes"],
    barcode: "8901030006789",
  },
  {
    id: "7",
    name: "Amlodipine",
    genericName: "Amlodipine Besylate",
    brand: "Norvasc",
    strength: "5mg",
    form: "Tablet",
    price: 95,
    manufacturer: "Pfizer",
    description: "Calcium channel blocker for hypertension",
    uses: ["High blood pressure", "Angina", "Coronary artery disease"],
    sideEffects: ["Ankle swelling", "Dizziness", "Flushing", "Fatigue"],
    dosage: "5-10mg once daily",
    precautions: ["Monitor blood pressure", "Rise slowly from sitting", "Regular heart checkups"],
    category: "Antihypertensive",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["high blood pressure", "hypertension", "angina", "chest pain", "heart disease"],
    barcode: "8901030007896",
  },
  {
    id: "8",
    name: "Enalapril",
    genericName: "Enalapril Maleate",
    brand: "Envas",
    strength: "5mg",
    form: "Tablet",
    price: 75,
    manufacturer: "Cadila",
    description: "ACE inhibitor for blood pressure control",
    uses: ["Hypertension", "Heart failure", "Kidney protection"],
    sideEffects: ["Dry cough", "Dizziness", "Hyperkalemia"],
    dosage: "5-10mg twice daily",
    precautions: ["Monitor kidney function", "Check potassium levels", "Avoid salt substitutes"],
    category: "ACE Inhibitor",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["high blood pressure", "hypertension", "heart failure", "kidney disease"],
    barcode: "8901030008903",
  },
  {
    id: "9",
    name: "Atenolol",
    genericName: "Atenolol",
    brand: "Tenormin",
    strength: "50mg",
    form: "Tablet",
    price: 65,
    manufacturer: "AstraZeneca",
    description: "Beta-blocker for heart conditions",
    uses: ["High blood pressure", "Angina", "Heart rhythm disorders"],
    sideEffects: ["Fatigue", "Cold hands/feet", "Slow heart rate"],
    dosage: "25-100mg once daily",
    precautions: ["Don't stop suddenly", "Monitor heart rate", "Caution in diabetes"],
    category: "Beta Blocker",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["high blood pressure", "angina", "heart rhythm problems", "palpitations"],
    barcode: "8901030009010",
  },
  {
    id: "10",
    name: "Salbutamol",
    genericName: "Salbutamol Sulfate",
    brand: "Asthalin",
    strength: "100mcg",
    form: "Inhaler",
    price: 145,
    manufacturer: "Cipla",
    description: "Bronchodilator for asthma and COPD",
    uses: ["Asthma", "COPD", "Bronchospasm", "Wheezing"],
    sideEffects: ["Tremor", "Palpitations", "Headache", "Nervousness"],
    dosage: "1-2 puffs every 4-6 hours as needed",
    precautions: ["Proper inhaler technique", "Rinse mouth after use", "Monitor heart rate"],
    category: "Bronchodilator",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["asthma", "wheezing", "shortness of breath", "copd", "bronchospasm", "cough"],
    barcode: "8901030010127",
  },
  {
    id: "11",
    name: "Montelukast",
    genericName: "Montelukast Sodium",
    brand: "Montair",
    strength: "10mg",
    form: "Tablet",
    price: 185,
    manufacturer: "Cipla",
    description: "Leukotriene receptor antagonist for asthma",
    uses: ["Asthma", "Allergic rhinitis", "Exercise-induced bronchospasm"],
    sideEffects: ["Headache", "Stomach pain", "Mood changes"],
    dosage: "10mg once daily in the evening",
    precautions: ["Monitor for mood changes", "Not for acute asthma attacks", "Take consistently"],
    category: "Anti-asthmatic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["asthma", "allergic rhinitis", "runny nose", "sneezing", "allergies"],
    barcode: "8901030011234",
  },
  {
    id: "12",
    name: "Omeprazole",
    genericName: "Omeprazole",
    brand: "Prilosec",
    strength: "20mg",
    form: "Capsule",
    price: 125,
    manufacturer: "Dr. Reddy's",
    description: "Proton pump inhibitor for acid-related disorders",
    uses: ["GERD", "Peptic ulcers", "Acid reflux", "Gastritis"],
    sideEffects: ["Headache", "Nausea", "Diarrhea", "Vitamin B12 deficiency"],
    dosage: "20-40mg once daily before breakfast",
    precautions: ["Take before meals", "Long-term use monitoring", "Calcium absorption"],
    category: "PPI",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["acid reflux", "heartburn", "stomach pain", "gastritis", "ulcer", "gerd"],
    barcode: "8901030012341",
  },
  {
    id: "13",
    name: "Domperidone",
    genericName: "Domperidone",
    brand: "Motilium",
    strength: "10mg",
    form: "Tablet",
    price: 85,
    manufacturer: "Johnson & Johnson",
    description: "Antiemetic and prokinetic agent",
    uses: ["Nausea", "Vomiting", "Gastroparesis", "Bloating"],
    sideEffects: ["Dry mouth", "Headache", "Breast tenderness"],
    dosage: "10mg three times daily before meals",
    precautions: ["Heart rhythm monitoring", "Avoid in liver disease", "Short-term use"],
    category: "Antiemetic",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["nausea", "vomiting", "stomach upset", "bloating", "gastroparesis"],
    barcode: "8901030013458",
  },
  {
    id: "14",
    name: "Loperamide",
    genericName: "Loperamide HCl",
    brand: "Imodium",
    strength: "2mg",
    form: "Capsule",
    price: 95,
    manufacturer: "Johnson & Johnson",
    description: "Antidiarrheal medication",
    uses: ["Diarrhea", "IBS with diarrhea", "Traveler's diarrhea"],
    sideEffects: ["Constipation", "Dizziness", "Nausea"],
    dosage: "2mg after each loose stool, max 16mg per day",
    precautions: ["Don't use in bacterial infections", "Avoid in fever", "Short-term use only"],
    category: "Antidiarrheal",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["diarrhea", "loose stools", "ibs", "stomach upset", "traveler's diarrhea"],
    barcode: "8901030014565",
  },
  // Expanded entries
  {
    id: "21",
    name: "Dolo 650",
    genericName: "Paracetamol",
    brand: "Dolo",
    strength: "650mg",
    form: "Tablet",
    price: 28,
    manufacturer: "Micro Labs",
    description: "Analgesic and antipyretic for fever and pain",
    uses: ["Fever", "Headache", "Body pain"],
    sideEffects: ["Nausea", "Rash", "Liver issues on overdose"],
    dosage: "1 tablet every 6-8 hours; do not exceed 4g/day acetaminophen",
    precautions: ["Avoid alcohol", "Check other meds for acetaminophen"],
    category: "Analgesic",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["fever", "headache", "body ache"],
    barcode: "8901234567001",
  },
  {
    id: "22",
    name: "Azithromycin",
    genericName: "Azithromycin",
    brand: "Azithral",
    strength: "500mg",
    form: "Tablet",
    price: 190,
    manufacturer: "Alembic",
    description: "Macrolide antibiotic",
    uses: ["Respiratory infections", "Skin infections"],
    sideEffects: ["Nausea", "Diarrhea", "Abdominal pain"],
    dosage: "500mg on day 1, then 250mg daily for 4 days (as advised)",
    precautions: ["Complete full course", "Drug interactions (QT prolongation)"],
    category: "Antibiotic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["bronchitis", "pneumonia", "skin infection"],
    barcode: "8901234567002",
  },
  {
    id: "23",
    name: "Amoxicillin + Clavulanate",
    genericName: "Amoxicillin/Clavulanic Acid",
    brand: "Augmentin",
    strength: "625mg",
    form: "Tablet",
    price: 220,
    manufacturer: "GSK",
    description: "Broad-spectrum antibiotic combo",
    uses: ["Bacterial infections", "ENT infections"],
    sideEffects: ["Diarrhea", "Rash", "Nausea"],
    dosage: "As prescribed; usually twice daily",
    precautions: ["Take with food", "Complete the course"],
    category: "Antibiotic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["throat infection", "sinusitis", "uti"],
    barcode: "8901234567003",
  },
  {
    id: "24",
    name: "Cetirizine",
    genericName: "Cetirizine HCl",
    brand: "Cetzine",
    strength: "10mg",
    form: "Tablet",
    price: 25,
    manufacturer: "GlaxoSmithKline",
    description: "Antihistamine for allergies",
    uses: ["Allergic rhinitis", "Urticaria"],
    sideEffects: ["Drowsiness", "Dry mouth"],
    dosage: "10mg once daily",
    precautions: ["Caution with driving if drowsy"],
    category: "Antihistamine",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["allergy", "runny nose", "itching"],
    barcode: "8901234567004",
  },
  {
    id: "25",
    name: "Pantoprazole",
    genericName: "Pantoprazole",
    brand: "Pantocid",
    strength: "40mg",
    form: "Tablet",
    price: 110,
    manufacturer: "Sun Pharma",
    description: "Proton pump inhibitor for acid suppression",
    uses: ["GERD", "Acid reflux", "Gastritis"],
    sideEffects: ["Headache", "Nausea"],
    dosage: "40mg once daily before breakfast",
    precautions: ["Long-term monitoring (B12, magnesium)"],
    category: "PPI",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["acid reflux", "heartburn", "gerd"],
    barcode: "8901234567005",
  },
  {
    id: "26",
    name: "Atorvastatin",
    genericName: "Atorvastatin",
    brand: "Atorlip",
    strength: "10mg",
    form: "Tablet",
    price: 95,
    manufacturer: "Cipla",
    description: "Statin to reduce cholesterol",
    uses: ["Hyperlipidemia", "Cardiovascular risk reduction"],
    sideEffects: ["Muscle pain", "Liver enzyme elevation"],
    dosage: "10-20mg once daily",
    precautions: ["Liver function monitoring", "Report muscle pain"],
    category: "Statin",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["high cholesterol", "cv risk"],
    barcode: "8901234567006",
  },
  {
    id: "27",
    name: "Levocetirizine",
    genericName: "Levocetirizine",
    brand: "Levocet",
    strength: "5mg",
    form: "Tablet",
    price: 30,
    manufacturer: "Torrent",
    description: "Non-sedating antihistamine",
    uses: ["Allergic rhinitis", "Chronic urticaria"],
    sideEffects: ["Drowsiness (less common)", "Dry mouth"],
    dosage: "5mg once daily in evening",
    precautions: ["Caution while driving"],
    category: "Antihistamine",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["allergy", "sneezing", "itching"],
    barcode: "8901234567007",
  },
  {
    id: "28",
    name: "Losartan",
    genericName: "Losartan Potassium",
    brand: "Losar",
    strength: "50mg",
    form: "Tablet",
    price: 80,
    manufacturer: "Unichem",
    description: "ARB for hypertension",
    uses: ["Hypertension", "Kidney protection in diabetes"],
    sideEffects: ["Dizziness", "High potassium"],
    dosage: "50mg once daily",
    precautions: ["Monitor kidney function and potassium"],
    category: "Antihypertensive",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["hypertension", "kidney protection"],
    barcode: "8901234567008",
  },
  {
    id: "29",
    name: "Metronidazole",
    genericName: "Metronidazole",
    brand: "Flagyl",
    strength: "400mg",
    form: "Tablet",
    price: 60,
    manufacturer: "Pfizer",
    description: "Antibiotic/antiprotozoal",
    uses: ["GI infections", "Anaerobic infections"],
    sideEffects: ["Metallic taste", "Nausea"],
    dosage: "As prescribed, often 2-3 times daily",
    precautions: ["Avoid alcohol", "Complete the course"],
    category: "Antibiotic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["diarrhea infection", "gi infection"],
    barcode: "8901234567009",
  },
  {
    id: "30",
    name: "Vitamin D3",
    genericName: "Cholecalciferol",
    brand: "D-Rise",
    strength: "60,000 IU",
    form: "Capsule",
    price: 45,
    manufacturer: "USV",
    description: "Vitamin supplementation",
    uses: ["Vitamin D deficiency", "Bone health"],
    sideEffects: ["Nausea (rare)", "Hypercalcemia (high doses)"],
    dosage: "Once weekly or as prescribed",
    precautions: ["Check levels if long-term"],
    category: "Supplement",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["vitamin d deficiency", "bone health"],
    barcode: "8901234567010",
  },
  {
    id: "31",
    name: "Ciprofloxacin",
    genericName: "Ciprofloxacin HCl",
    brand: "Cipro",
    strength: "500mg",
    form: "Tablet",
    price: 110,
    manufacturer: "Bayer",
    description: "Fluoroquinolone antibiotic for bacterial infections",
    uses: ["UTI", "Respiratory infections", "Ear infections"],
    sideEffects: ["Nausea", "Diarrhea", "Tendon problems"],
    dosage: "500mg twice daily for 5-7 days",
    precautions: ["Avoid if tendon issues", "Avoid dairy products"],
    category: "Antibiotic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["uti", "respiratory infection", "ear infection"],
    barcode: "8901234567011",
  },
  {
    id: "32",
    name: "Loratadine",
    genericName: "Loratadine",
    brand: "Claritin",
    strength: "10mg",
    form: "Tablet",
    price: 35,
    manufacturer: "Schering-Plough",
    description: "Non-drowsy antihistamine for allergies",
    uses: ["Allergic rhinitis", "Urticaria", "Seasonal allergies"],
    sideEffects: ["Dry mouth", "Headache"],
    dosage: "10mg once daily",
    precautions: ["Take same time daily"],
    category: "Antihistamine",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["allergy", "hay fever", "seasonal allergies"],
    barcode: "8901234567012",
  },
  {
    id: "33",
    name: "Ranitidine",
    genericName: "Ranitidine HCl",
    brand: "Zantac",
    strength: "150mg",
    form: "Tablet",
    price: 40,
    manufacturer: "GSK",
    description: "H2 receptor blocker for acid reflux",
    uses: ["Heartburn", "GERD", "Ulcers"],
    sideEffects: ["Headache", "Nausea"],
    dosage: "150mg twice daily",
    precautions: ["Take with water", "Regular monitoring"],
    category: "Antihistamine H2",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["heartburn", "acid reflux", "ulcer"],
    barcode: "8901234567013",
  },
  {
    id: "34",
    name: "Fluconazole",
    genericName: "Fluconazole",
    brand: "Diflucan",
    strength: "150mg",
    form: "Tablet",
    price: 250,
    manufacturer: "Pfizer",
    description: "Antifungal medication",
    uses: ["Yeast infections", "Fungal infections"],
    sideEffects: ["Headache", "Nausea", "Rash"],
    dosage: "150mg as single dose",
    precautions: ["Check liver function", "Avoid in pregnancy"],
    category: "Antifungal",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["fungal infection", "yeast infection"],
    barcode: "8901234567014",
  },
  {
    id: "35",
    name: "Diclofenac",
    genericName: "Diclofenac Sodium",
    brand: "Voveran",
    strength: "50mg",
    form: "Tablet",
    price: 50,
    manufacturer: "Novartis",
    description: "NSAID for inflammation and pain",
    uses: ["Joint pain", "Muscle pain", "Fever"],
    sideEffects: ["Stomach upset", "Headache"],
    dosage: "50mg 2-3 times daily with food",
    precautions: ["Take with food", "Avoid alcohol"],
    category: "NSAID",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["joint pain", "muscle pain", "arthritis"],
    barcode: "8901234567015",
  },
  {
    id: "36",
    name: "Amoxicillin",
    genericName: "Amoxicillin Trihydrate",
    brand: "Moxiflox",
    strength: "500mg",
    form: "Capsule",
    price: 80,
    manufacturer: "Cipla",
    description: "Beta-lactam antibiotic",
    uses: ["Strep throat", "Ear infections", "Pneumonia"],
    sideEffects: ["Nausea", "Diarrhea", "Rash"],
    dosage: "500mg three times daily for 7-10 days",
    precautions: ["Complete full course", "Report rash"],
    category: "Antibiotic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["throat infection", "ear infection", "pneumonia"],
    barcode: "8901234567016",
  },
  {
    id: "37",
    name: "Cefixime",
    genericName: "Cefixime Trihydrate",
    brand: "Suprax",
    strength: "200mg",
    form: "Tablet",
    price: 140,
    manufacturer: "Lupin",
    description: "Third-generation cephalosporin antibiotic",
    uses: ["UTI", "Respiratory tract infections"],
    sideEffects: ["Nausea", "Diarrhea"],
    dosage: "200mg twice daily",
    precautions: ["Complete course", "Cross-reactivity in penicillin allergy"],
    category: "Antibiotic",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["uti", "respiratory infection"],
    barcode: "8901234567017",
  },
  {
    id: "38",
    name: "Mometasone",
    genericName: "Mometasone Furoate",
    brand: "Asmanex",
    strength: "220mcg",
    form: "Inhaler",
    price: 200,
    manufacturer: "Merck",
    description: "Corticosteroid inhaler for asthma",
    uses: ["Asthma", "COPD", "Bronchitis"],
    sideEffects: ["Oral thrush", "Hoarseness"],
    dosage: "1-2 inhalations daily",
    precautions: ["Rinse mouth after use", "Regular monitoring"],
    category: "Corticosteroid",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["asthma", "copd", "wheezing"],
    barcode: "8901234567018",
  },
  {
    id: "39",
    name: "Ketoconazole",
    genericName: "Ketoconazole",
    brand: "Nizoral",
    strength: "200mg",
    form: "Tablet",
    price: 180,
    manufacturer: "Johnson & Johnson",
    description: "Antifungal for systemic infections",
    uses: ["Fungal infections", "Candidiasis"],
    sideEffects: ["Nausea", "Liver issues"],
    dosage: "200mg daily",
    precautions: ["Monitor liver enzymes", "Avoid alcohol"],
    category: "Antifungal",
    prescriptionRequired: true,
    availability: "In Stock",
    conditions: ["fungal infection", "candida"],
    barcode: "8901234567019",
  },
  {
    id: "40",
    name: "Sucralfate",
    genericName: "Sucralfate",
    brand: "Carafate",
    strength: "1g",
    form: "Tablet",
    price: 70,
    manufacturer: "Allergan",
    description: "Protective medication for ulcers",
    uses: ["Peptic ulcers", "GERD", "Ulcer prevention"],
    sideEffects: ["Constipation", "Nausea"],
    dosage: "1g four times daily",
    precautions: ["Take on empty stomach", "Separate from other meds"],
    category: "Antacid",
    prescriptionRequired: false,
    availability: "In Stock",
    conditions: ["ulcer", "acid reflux"],
    barcode: "8901234567020",
  },
]

// Helper functions for autocomplete and suggestions
export function getMedicineSuggestions(query: string): string[] {
  if (!query.trim()) return []

  const searchTerm = query.toLowerCase()
  const suggestions = new Set<string>()

  medicineDatabase.forEach((medicine) => {
    if (medicine.name.toLowerCase().includes(searchTerm)) {
      suggestions.add(medicine.name)
    }
    if (medicine.genericName.toLowerCase().includes(searchTerm)) {
      suggestions.add(medicine.genericName)
    }
    if (medicine.brand.toLowerCase().includes(searchTerm)) {
      suggestions.add(medicine.brand)
    }
  })

  return Array.from(suggestions).slice(0, 10).sort()
}

export function getConditionSuggestions(query: string): string[] {
  if (!query.trim()) return []

  const searchTerm = query.toLowerCase()
  const suggestions = new Set<string>()

  medicineDatabase.forEach((medicine) => {
    medicine.conditions.forEach((condition) => {
      if (condition.toLowerCase().includes(searchTerm)) {
        suggestions.add(condition)
      }
    })
  })

  return Array.from(suggestions).slice(0, 10).sort()
}

export function searchMedicines(query: string): Medicine[] {
  if (!query.trim()) return medicineDatabase

  const searchTerm = query.toLowerCase().trim()

  return medicineDatabase.filter((medicine) => {
    const searchFields = [
      medicine.name.toLowerCase(),
      medicine.genericName.toLowerCase(),
      medicine.brand.toLowerCase(),
      medicine.category.toLowerCase(),
      ...medicine.uses.map((use) => use.toLowerCase()),
      ...medicine.conditions.map((condition) => condition.toLowerCase()),
    ]

    return searchFields.some(
      (field) => field.includes(searchTerm) || searchTerm.split(" ").every((term) => field.includes(term)),
    )
  })
}

export function searchMedicinesByCondition(condition: string): Medicine[] {
  if (!condition.trim()) return []

  const conditionTerm = condition.toLowerCase().trim()

  return medicineDatabase
    .filter((medicine) =>
      medicine.conditions.some(
        (cond) => cond.toLowerCase().includes(conditionTerm) || conditionTerm.includes(cond.toLowerCase()),
      ),
    )
    .sort((a, b) => {
      const aExactMatch = a.conditions.some((cond) => cond.toLowerCase() === conditionTerm)
      const bExactMatch = b.conditions.some((cond) => cond.toLowerCase() === conditionTerm)
      if (aExactMatch && !bExactMatch) return -1
      if (!aExactMatch && bExactMatch) return 1
      return 0
    })
}

export function searchMedicineByBarcode(barcode: string): Medicine | null {
  return medicineDatabase.find((medicine) => medicine.barcode === barcode) || null
}

export function getMedicineById(id: string): Medicine | null {
  return medicineDatabase.find((medicine) => medicine.id === id) || null
}

export function getMedicinesByCategory(category: string): Medicine[] {
  return medicineDatabase.filter((medicine) => medicine.category.toLowerCase() === category.toLowerCase())
}

export function getAvailableMedicines(): Medicine[] {
  return medicineDatabase.filter((medicine) => medicine.availability === "In Stock")
}

export function getPrescriptionMedicines(): Medicine[] {
  return medicineDatabase.filter((medicine) => medicine.prescriptionRequired)
}

export function getOTCMedicines(): Medicine[] {
  return medicineDatabase.filter((medicine) => !medicine.prescriptionRequired)
}
